

# Quiz 2 Review




## Overview

Our first quiz covers sections 2.1 - 2.3  and 4.1-4.6 in Lay's book. This corresponds to Problem Sets 4 and 5.


### Vocabulary and Concepts



You should understand these concepts and be able to read and use these terms correctly:

* all of the [Important Definitions found here][Important Definitions].
* matrix inverses
* the Invertible Matrix Theorem
* homogeneous coordinates
* subspaces
* null space and column space of a matrix
* kernel and image of a linear transformation
* basis (span and linearly independent)
* coordinate vector with respect to a basis $\mathcal{B}$
* change-of-coordinates matrix
* dimension



### Skills

You should be able to perform these linear algebra tasks.

* solve matrix algebra equations
* find a matrix inverse
* use homogeneous coordinates to transform and translate images in the plane.
* show that a subset is a subspace or demonstrate that it is not a subspace
* describe the null space and the column space
* determine if a vector is in a null space or column space
* find a basis of a subspace
* answer questions about the connections between all these ideas
* write short proofs of basic statements using the important definitions


## Practice Problems



1. Find the inverse of the matrix
$$
\left[
\begin{array}{rrr}
1 & -2 & 2  \\
1 & 0 & 0 \\
2 &-4 & 5
\end{array}
\right]
$$



1. Suppose that a linear transformation $T: \mathbb{R}^n \rightarrow \mathbb{R}^n$ has the property that 
$T(\mathsf{u}) = T(\mathsf{v})$ for some pair of distinct vectors $\mathsf{u}, \mathsf{v} \in \mathbb{R}^n$. Can $T$ map $\mathbb{R}^n$ onto $\mathbb{R}^n$? Why or why not?


1. Let $U$ and $W$ be subspaces of a vector space $\mathbb{R}^n$. 
Prove or disprove the following statements
    a. $U \cap W = \{ \mathsf{v} \in V \mid \mathsf{v} \in U \mbox{ and } \mathsf{v} \in W \}$ is a subspace
    b. $U \cup W = \{ \mathsf{v} \in V \mid \mathsf{v} \in U \mbox{ or } \mathsf{v} \in W \}$ is a subspace
    c. $U+W = \{\mathsf{u} + \mathsf{w} \mid \mathsf{u} \in U \mbox{ and } \mathsf{w} \in W \}$ is a subspace




1. Let $T: \mathbb{R}^n \rightarrow \mathbb{R}^m$ be a linear transformation. 

    a. Suppose that $T: \mathbb{R}^n \to \mathbb{R}^m$ is one-to-one. Prove that if $\mathsf{v}_1, \ldots, \mathsf{v}_k$ are linearly independent, then $T(\mathsf{v}_1), T(\mathsf{v}_2), \ldots, T(\mathsf{v}_k)$ are linearly independent.

    b. Suppose that $T: \mathbb{R}^n \to \mathbb{R}^m$ is onto. Prove that if $\mathsf{v}_1, \ldots, \mathsf{v}_k$ span $\mathbb{R}^n$ then $T(\mathsf{v}_1), T(\mathsf{v}_2), \ldots, T(\mathsf{v}_k)$ span $\mathbb{R}^m$.




1.  I have performed some row operations below for you on a matrix $A$. Find a basis for the column space and the null space of $A$. 
$$
A=
\left[
\begin{matrix}
1& 2& 0& 2& 0& -1 \\
1& 2& 1& 1& 0& -2 \\
2& 4& -2& 6& 1& 2 \\
1& 2&  0& 2& -1& -3 \\
\end{matrix}\right] \longrightarrow
\left[
\begin{matrix}
1& 2& 0& 2& 0& -1\\
0& 0& 1& -1& 0& -1\\
0& 0& 0& 0& 1& 2\\
0& 0&   0& 0& 0& 0\\
\end{matrix}\right] 
$$   





1. Consider the matrix 
\[
A = \left[
\begin{array}{cccc}
1 & 5 & 2 & -4 \\
3 & 10 & 2 & 8 \\
4 & 15 & 4 & 4 
\end{array}
\right]
\]
Find a basis for $\mathrm{Col}(A)$. Find a basis for $\mathrm{Nul}(A)$.



1. Are the vectors in ${\mathcal B}$ a basis of $\mathbb{R}^3$? If not, find a basis of $\mathbb{R}^3$ that consists of as many of the vectors from ${\mathcal B}$ as is possible. Explain your reasoning.
$$
\mathcal{B}=\left\{ \begin{bmatrix} 1 \\ -1 \\ -2 \end{bmatrix},\begin{bmatrix} 2 \\ -1 \\ 1 \end{bmatrix},\begin{bmatrix} -1 \\ -1 \\ -8 \end{bmatrix}
\right\}
$$

1. I have the vectors below: 
$$
\begin{bmatrix} 5\\ 4\\ 3\\ 1\\ 2 \end{bmatrix}, \begin{bmatrix} 4\\ 4\\ 3\\ 1\\ 2 \end{bmatrix}, \begin{bmatrix} 1\\ 1\\ 1\\ 1\\ 1\end{bmatrix}. 
$$
I know that they do not span $\mathbb{R}^5$, but  I want to extend them to a basis of $\mathbb{R}^5$ by adding some vectors to the set. I created the  matrix below and row reduced. Give a basis for $\mathbb{R}^5$ that uses my three vectors and explain why this method works in general.
$$
\left[
\begin{array}{cccccccc}
 5 & 4 & 1 & 1 & 0 & 0 & 0 & 0 \\
 4 & 4 & 1 & 0 & 1 & 0 & 0 & 0 \\
 3 & 3 & 1 & 0 & 0 & 1 & 0 & 0 \\
 1 & 1 & 1 & 0 & 0 & 0 & 1 & 0 \\
 2 & 2 & 1 & 0 & 0 & 0 & 0 & 1 \\
\end{array}
\right] \rightarrow \left[
\begin{array}{cccccccc}
 1 & 0 & 0 & 1 & 0 & 0 & 2 & -3 \\
 0 & 1 & 0 & -1 & 0 & 0 & -3 & 4 \\
 0 & 0 & 1 & 0 & 0 & 0 & 2 & -1 \\
 0 & 0 & 0 & 0 & 1 & 0 & 2 & -3 \\
 0 & 0 & 0 & 0 & 0 & 1 & 1 & -2 \\
\end{array}
\right]
$$

1. Find the coordinates of $\mathsf{w}$ in the standard basis and of $\mathsf{v}$ in the $\mathcal{B}$-basis.
$$
\mathcal{B} = \left\{
\mathsf{v}_1=\begin{bmatrix} 1 \\ 0 \\ 0 \\ 0 \end{bmatrix},
\mathsf{v}_2=\begin{bmatrix} 1 \\ 1 \\ 0 \\ 0 \end{bmatrix},
\mathsf{v}_3=\begin{bmatrix} 1 \\ 1 \\ 1 \\ 0 \end{bmatrix},
\mathsf{v}_4=\begin{bmatrix} 1 \\ 1 \\ 1 \\ 1 \end{bmatrix}
\right\},
\qquad
\mathsf{w} = 
\begin{bmatrix} 3 \\ -2 \\ 0 \\ -1 \end{bmatrix}_{\mathcal{B}},
\qquad
\mathsf{v} = 
\begin{bmatrix} 10 \\ 9 \\ 7 \\ 4 \end{bmatrix}_{\mathcal{S}}
$$

1.  The subspace $S \subset \mathbb{R}^5$ is given by 
$$ \mathsf{S} = \mathsf{span}
\left(
\begin{bmatrix}1\\ 1\\ 0\\ -1\\ 2 \end{bmatrix},
\begin{bmatrix} 0\\ 1\\ 1\\  1\\ 1 \end{bmatrix},
\begin{bmatrix} 3\\ 1\\ -2\\ -5\\ 4 \end{bmatrix},
\begin{bmatrix} 1\\ 0\\ 1\\ 0\\ 1 \end{bmatrix},
\begin{bmatrix} 2\\ -1\\ -1\\ -3\\ 1 \end{bmatrix},
\right)$$

    a. Use the following matrix to find a basis for $S$. What is the dimension of  $S$?
$$
A=\left[
\begin{array}{ccccc}
 1 & 0 & 3 & 1 & 2 \\
 1 & 1 & 1 & 0 & -1 \\
 0 & 1 & -2 & 1 & -1 \\
 -1 & 1 & -5 & 0 & -3 \\
 2 & 1 & 4 & 1 & 1 \\
\end{array}
\right] \rightarrow
\left[
\begin{array}{ccccc}
 1 & 0 & 3 & 0 & 1 \\
 0 & 1 & -2 & 0 & -2 \\
 0 & 0 & 0 & 1 & 1 \\
 0 & 0 & 0 & 0 & 0 \\
 0 & 0 & 0 & 0 & 0 \\
\end{array}
\right]
$$

    a. Find a basis for $\mathrm{Nul}(A)$. What is the dimension of this nullspace?

1. A $5 \times 7$ matrix $A$ contains 5 pivots. For each of  $\mathrm{Col}(A)$ and $\mathrm{Nul}(A)$,

    *  Determine the dimension of the subspace,
    * Indicate whether it is  subspace of $\mathbb{R}^5$ or $\mathbb{R}^7$, and 
    * Decide how you would find a basis of the space.  Answer your question as follows.




## Solutions to Practice Problems


