<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Vector 26 Quiz 3 Review | MATH 236: Linear Algebra</title>
  <meta name="description" content="This is the class activity manual for MATH 236 at Macalester College." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Vector 26 Quiz 3 Review | MATH 236: Linear Algebra" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is the class activity manual for MATH 236 at Macalester College." />
  <meta name="github-repo" content="mathbeveridge/math236_f20" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Vector 26 Quiz 3 Review | MATH 236: Linear Algebra" />
  
  <meta name="twitter:description" content="This is the class activity manual for MATH 236 at Macalester College." />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="quiz-2-review.html"/>

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; } /* Alert */
code span.an { color: #008000; } /* Annotation */
code span.at { } /* Attribute */
code span.bu { } /* BuiltIn */
code span.cf { color: #0000ff; } /* ControlFlow */
code span.ch { color: #008080; } /* Char */
code span.cn { } /* Constant */
code span.co { color: #008000; } /* Comment */
code span.cv { color: #008000; } /* CommentVar */
code span.do { color: #008000; } /* Documentation */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.im { } /* Import */
code span.in { color: #008000; } /* Information */
code span.kw { color: #0000ff; } /* Keyword */
code span.op { } /* Operator */
code span.ot { color: #ff4000; } /* Other */
code span.pp { color: #ff4000; } /* Preprocessor */
code span.sc { color: #008080; } /* SpecialChar */
code span.ss { color: #008080; } /* SpecialString */
code span.st { color: #008080; } /* String */
code span.va { } /* Variable */
code span.vs { color: #008080; } /* VerbatimString */
code span.wa { color: #008000; font-weight: bold; } /* Warning */
</style>

<link rel="stylesheet" href="m236.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href = "./">MATH 236: Linear Algebra</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="part"><span><b>I Problem Sets</b></span></li>
<li class="chapter" data-level="1" data-path="problem-set-1.html"><a href="problem-set-1.html"><i class="fa fa-check"></i><b>1</b> Problem Set 1</a><ul>
<li class="chapter" data-level="1.1" data-path="problem-set-1.html"><a href="problem-set-1.html#characterize-the-solution-set"><i class="fa fa-check"></i><b>1.1</b> Characterize the Solution Set</a></li>
<li class="chapter" data-level="1.2" data-path="problem-set-1.html"><a href="problem-set-1.html#find-the-parametric-solution"><i class="fa fa-check"></i><b>1.2</b> Find the Parametric Solution</a></li>
<li class="chapter" data-level="1.3" data-path="problem-set-1.html"><a href="problem-set-1.html#elementary-row-operations-are-reversible"><i class="fa fa-check"></i><b>1.3</b> Elementary row operations are reversible</a></li>
<li class="chapter" data-level="1.4" data-path="problem-set-1.html"><a href="problem-set-1.html#traffic-flow"><i class="fa fa-check"></i><b>1.4</b> Traffic Flow</a></li>
<li class="chapter" data-level="1.5" data-path="problem-set-1.html"><a href="problem-set-1.html#parabolas-through-two-points"><i class="fa fa-check"></i><b>1.5</b> Parabolas Through Two Points</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="problem-set-2.html"><a href="problem-set-2.html"><i class="fa fa-check"></i><b>2</b> Problem Set 2</a><ul>
<li class="chapter" data-level="2.1" data-path="problem-set-2.html"><a href="problem-set-2.html#parametric-vector-form"><i class="fa fa-check"></i><b>2.1</b> Parametric Vector Form</a></li>
<li class="chapter" data-level="2.2" data-path="problem-set-2.html"><a href="problem-set-2.html#rref-for-a-linear-system"><i class="fa fa-check"></i><b>2.2</b> RREF for a linear system</a></li>
<li class="chapter" data-level="2.3" data-path="problem-set-2.html"><a href="problem-set-2.html#rref-for-a-set-of-vectors"><i class="fa fa-check"></i><b>2.3</b> RREF for a set of vectors</a></li>
<li class="chapter" data-level="2.4" data-path="problem-set-2.html"><a href="problem-set-2.html#removing-free-variable-columns-from-a-matrix"><i class="fa fa-check"></i><b>2.4</b> Removing free variable columns from a matrix</a></li>
<li class="chapter" data-level="2.5" data-path="problem-set-2.html"><a href="problem-set-2.html#a-square-matrix"><i class="fa fa-check"></i><b>2.5</b> A square matrix</a></li>
<li class="chapter" data-level="2.6" data-path="problem-set-2.html"><a href="problem-set-2.html#combining-solutions-to-a-mathsfx-mathsfb"><i class="fa fa-check"></i><b>2.6</b> Combining solutions to <span class="math inline">\(A \mathsf{x} = \mathsf{b}\)</span></a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="problem-set-3.html"><a href="problem-set-3.html"><i class="fa fa-check"></i><b>3</b> Problem Set 3</a><ul>
<li class="chapter" data-level="3.1" data-path="problem-set-3.html"><a href="problem-set-3.html#three-vectors-in-mathbbr4"><i class="fa fa-check"></i><b>3.1</b> Three vectors in <span class="math inline">\(\mathbb{R}^4\)</span></a></li>
<li class="chapter" data-level="3.2" data-path="problem-set-3.html"><a href="problem-set-3.html#a-balanced-diet"><i class="fa fa-check"></i><b>3.2</b> A Balanced Diet</a></li>
<li class="chapter" data-level="3.3" data-path="problem-set-3.html"><a href="problem-set-3.html#a-problem-about-span-and-linear-dependence"><i class="fa fa-check"></i><b>3.3</b> A Problem about Span and Linear Dependence</a></li>
<li class="chapter" data-level="3.4" data-path="problem-set-3.html"><a href="problem-set-3.html#properties-of-linear-transformations"><i class="fa fa-check"></i><b>3.4</b> Properties of Linear Transformations</a></li>
<li class="chapter" data-level="3.5" data-path="problem-set-3.html"><a href="problem-set-3.html#partial-information-about-a-linear-transformation"><i class="fa fa-check"></i><b>3.5</b> Partial Information about a Linear Transformation</a></li>
<li class="chapter" data-level="3.6" data-path="problem-set-3.html"><a href="problem-set-3.html#house-renovations"><i class="fa fa-check"></i><b>3.6</b> House Renovations</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="problem-set-4.html"><a href="problem-set-4.html"><i class="fa fa-check"></i><b>4</b> Problem Set 4</a><ul>
<li class="chapter" data-level="4.1" data-path="problem-set-4.html"><a href="problem-set-4.html#an-invertible-product-of-rectangular-matrices"><i class="fa fa-check"></i><b>4.1</b> An Invertible Product of Rectangular Matrices</a></li>
<li class="chapter" data-level="4.2" data-path="problem-set-4.html"><a href="problem-set-4.html#guessing-the-inverse-matrix-from-a-pattern"><i class="fa fa-check"></i><b>4.2</b> Guessing the Inverse Matrix from a Pattern</a></li>
<li class="chapter" data-level="4.3" data-path="problem-set-4.html"><a href="problem-set-4.html#lu-decomposition-of-an-invertible-matrix"><i class="fa fa-check"></i><b>4.3</b> LU Decomposition of an Invertible Matrix</a></li>
<li class="chapter" data-level="4.4" data-path="problem-set-4.html"><a href="problem-set-4.html#homogeneous-coordinates"><i class="fa fa-check"></i><b>4.4</b> Homogeneous Coordinates</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="problem-set-5.html"><a href="problem-set-5.html"><i class="fa fa-check"></i><b>5</b> Problem Set 5</a><ul>
<li class="chapter" data-level="5.1" data-path="problem-set-5.html"><a href="problem-set-5.html#a-subspace-from-two-linear-transformations"><i class="fa fa-check"></i><b>5.1</b> A Subspace from Two Linear Transformations</a></li>
<li class="chapter" data-level="5.2" data-path="problem-set-5.html"><a href="problem-set-5.html#getting-into-a-subspace"><i class="fa fa-check"></i><b>5.2</b> Getting Into a Subspace</a></li>
<li class="chapter" data-level="5.3" data-path="problem-set-5.html"><a href="problem-set-5.html#creating-a-basis-from-another-basis."><i class="fa fa-check"></i><b>5.3</b> Creating a Basis from Another Basis.</a></li>
<li class="chapter" data-level="5.4" data-path="problem-set-5.html"><a href="problem-set-5.html#a-vector-that-is-in-both-cola-and-nula"><i class="fa fa-check"></i><b>5.4</b> A Vector that is in Both Col(A) and Nul}(A)</a></li>
<li class="chapter" data-level="5.5" data-path="problem-set-5.html"><a href="problem-set-5.html#changing-coordinate-systems"><i class="fa fa-check"></i><b>5.5</b> Changing Coordinate Systems</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="problem-set-6.html"><a href="problem-set-6.html"><i class="fa fa-check"></i><b>6</b> Problem Set 6</a><ul>
<li class="chapter" data-level="6.1" data-path="problem-set-6.html"><a href="problem-set-6.html#the-square-root-of-a-matrix"><i class="fa fa-check"></i><b>6.1</b> The Square Root of a Matrix?</a></li>
<li class="chapter" data-level="6.2" data-path="problem-set-6.html"><a href="problem-set-6.html#a-matrix-mystery"><i class="fa fa-check"></i><b>6.2</b> A Matrix Mystery</a></li>
<li class="chapter" data-level="6.3" data-path="problem-set-6.html"><a href="problem-set-6.html#upper-triangular-matrix-with-a-constant-diagonal"><i class="fa fa-check"></i><b>6.3</b> Upper Triangular Matrix with a Constant Diagonal</a></li>
<li class="chapter" data-level="6.4" data-path="problem-set-6.html"><a href="problem-set-6.html#block-diagonalization-of-a-4-times-4-matrix"><i class="fa fa-check"></i><b>6.4</b> Block Diagonalization of a <span class="math inline">\(4 \times 4\)</span> Matrix</a></li>
<li class="chapter" data-level="6.5" data-path="problem-set-6.html"><a href="problem-set-6.html#network-analysis-of-risk-territories"><i class="fa fa-check"></i><b>6.5</b> Network Analysis of Risk Territories</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="problem-set-7.html"><a href="problem-set-7.html"><i class="fa fa-check"></i><b>7</b> Problem Set 7</a><ul>
<li class="chapter" data-level="7.1" data-path="problem-set-7.html"><a href="problem-set-7.html#glucose-insulin-system-model"><i class="fa fa-check"></i><b>7.1</b> Glucose-Insulin System Model</a></li>
<li class="chapter" data-level="7.2" data-path="problem-set-7.html"><a href="problem-set-7.html#population-interaction-models"><i class="fa fa-check"></i><b>7.2</b> Population Interaction Models</a></li>
<li class="chapter" data-level="7.3" data-path="problem-set-7.html"><a href="problem-set-7.html#blue-whale-population-dynamics"><i class="fa fa-check"></i><b>7.3</b> Blue Whale Population Dynamics</a></li>
<li class="chapter" data-level="7.4" data-path="problem-set-7.html"><a href="problem-set-7.html#the-power-method-for-eigenvalue-calculation"><i class="fa fa-check"></i><b>7.4</b> The Power Method for Eigenvalue Calculation</a></li>
</ul></li>
<li class="part"><span><b>II Concepts of Linear Algebra</b></span></li>
<li class="chapter" data-level="8" data-path="important-definitions.html"><a href="important-definitions.html"><i class="fa fa-check"></i><b>8</b> Important Definitions</a></li>
<li class="chapter" data-level="9" data-path="week-1-learning-goals.html"><a href="week-1-learning-goals.html"><i class="fa fa-check"></i><b>9</b> Week 1 Learning Goals</a><ul>
<li class="chapter" data-level="9.1" data-path="week-1-learning-goals.html"><a href="week-1-learning-goals.html#solving-linear-equations"><i class="fa fa-check"></i><b>9.1</b> Solving Linear Equations</a></li>
<li class="chapter" data-level="9.2" data-path="week-1-learning-goals.html"><a href="week-1-learning-goals.html#vocabulary"><i class="fa fa-check"></i><b>9.2</b> Vocabulary</a></li>
<li class="chapter" data-level="9.3" data-path="week-1-learning-goals.html"><a href="week-1-learning-goals.html#conceptual-thinking"><i class="fa fa-check"></i><b>9.3</b> Conceptual Thinking</a></li>
<li class="chapter" data-level="9.4" data-path="week-1-learning-goals.html"><a href="week-1-learning-goals.html#rstudio"><i class="fa fa-check"></i><b>9.4</b> RStudio</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="week-2-learning-goals.html"><a href="week-2-learning-goals.html"><i class="fa fa-check"></i><b>10</b> Week 2 Learning Goals</a><ul>
<li class="chapter" data-level="10.1" data-path="week-2-learning-goals.html"><a href="week-2-learning-goals.html#solution-sets-span-and-linear-independence"><i class="fa fa-check"></i><b>10.1</b> Solution Sets, Span and Linear Independence</a></li>
<li class="chapter" data-level="10.2" data-path="week-2-learning-goals.html"><a href="week-2-learning-goals.html#vocabulary-1"><i class="fa fa-check"></i><b>10.2</b> Vocabulary</a></li>
<li class="chapter" data-level="10.3" data-path="week-2-learning-goals.html"><a href="week-2-learning-goals.html#conceptual-thinking-1"><i class="fa fa-check"></i><b>10.3</b> Conceptual Thinking</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="week-3-learning-goals.html"><a href="week-3-learning-goals.html"><i class="fa fa-check"></i><b>11</b> Week 3 Learning Goals</a><ul>
<li class="chapter" data-level="11.1" data-path="week-3-learning-goals.html"><a href="week-3-learning-goals.html#linear-transformations-and-matrix-inverses"><i class="fa fa-check"></i><b>11.1</b> Linear Transformations and Matrix Inverses</a></li>
<li class="chapter" data-level="11.2" data-path="week-3-learning-goals.html"><a href="week-3-learning-goals.html#vocabulary-2"><i class="fa fa-check"></i><b>11.2</b> Vocabulary</a></li>
<li class="chapter" data-level="11.3" data-path="week-3-learning-goals.html"><a href="week-3-learning-goals.html#conceptual-thinking-2"><i class="fa fa-check"></i><b>11.3</b> Conceptual Thinking</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="week-4-learning-goals.html"><a href="week-4-learning-goals.html"><i class="fa fa-check"></i><b>12</b> Week 4 Learning Goals</a><ul>
<li class="chapter" data-level="12.1" data-path="week-4-learning-goals.html"><a href="week-4-learning-goals.html#vector-spaces-and-the-determinant"><i class="fa fa-check"></i><b>12.1</b> Vector Spaces and the Determinant</a></li>
<li class="chapter" data-level="12.2" data-path="week-4-learning-goals.html"><a href="week-4-learning-goals.html#vocabulary-3"><i class="fa fa-check"></i><b>12.2</b> Vocabulary</a></li>
<li class="chapter" data-level="12.3" data-path="week-4-learning-goals.html"><a href="week-4-learning-goals.html#conceptual-thinking-3"><i class="fa fa-check"></i><b>12.3</b> Conceptual Thinking</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="week-5-6-learning-goals.html"><a href="week-5-6-learning-goals.html"><i class="fa fa-check"></i><b>13</b> Week 5-6 Learning Goals</a><ul>
<li class="chapter" data-level="13.1" data-path="week-5-6-learning-goals.html"><a href="week-5-6-learning-goals.html#eigensystems"><i class="fa fa-check"></i><b>13.1</b> Eigensystems</a></li>
<li class="chapter" data-level="13.2" data-path="week-5-6-learning-goals.html"><a href="week-5-6-learning-goals.html#vocabulary-4"><i class="fa fa-check"></i><b>13.2</b> Vocabulary</a></li>
<li class="chapter" data-level="13.3" data-path="week-5-6-learning-goals.html"><a href="week-5-6-learning-goals.html#conceptual-thinking-4"><i class="fa fa-check"></i><b>13.3</b> Conceptual Thinking</a></li>
</ul></li>
<li class="part"><span><b>III LineaR Algebra</b></span></li>
<li class="chapter" data-level="14" data-path="linear-systems-in-r.html"><a href="linear-systems-in-r.html"><i class="fa fa-check"></i><b>14</b> Linear Systems in R</a><ul>
<li class="chapter" data-level="14.1" data-path="linear-systems-in-r.html"><a href="linear-systems-in-r.html#building-vectors-and-matrices"><i class="fa fa-check"></i><b>14.1</b> Building Vectors and Matrices</a></li>
<li class="chapter" data-level="14.2" data-path="linear-systems-in-r.html"><a href="linear-systems-in-r.html#solving-a-linear-system"><i class="fa fa-check"></i><b>14.2</b> Solving a Linear System</a></li>
<li class="chapter" data-level="14.3" data-path="linear-systems-in-r.html"><a href="linear-systems-in-r.html#solving-another-linear-system"><i class="fa fa-check"></i><b>14.3</b> Solving another Linear System</a></li>
<li class="chapter" data-level="14.4" data-path="linear-systems-in-r.html"><a href="linear-systems-in-r.html#appendix-dimensionless-vectors-in-r"><i class="fa fa-check"></i><b>14.4</b> Appendix: Dimensionless Vectors in R</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="d-linear-transformations.html"><a href="d-linear-transformations.html"><i class="fa fa-check"></i><b>15</b> 2D Linear Transformations</a><ul>
<li class="chapter" data-level="15.1" data-path="d-linear-transformations.html"><a href="d-linear-transformations.html#functions-to-plot-our-vectors"><i class="fa fa-check"></i><b>15.1</b> Functions to plot our vectors</a></li>
<li class="chapter" data-level="15.2" data-path="d-linear-transformations.html"><a href="d-linear-transformations.html#your-turn"><i class="fa fa-check"></i><b>15.2</b> Your Turn</a><ul>
<li class="chapter" data-level="15.2.1" data-path="d-linear-transformations.html"><a href="d-linear-transformations.html#family-1"><i class="fa fa-check"></i><b>15.2.1</b> Family 1</a></li>
<li class="chapter" data-level="15.2.2" data-path="d-linear-transformations.html"><a href="d-linear-transformations.html#family-2"><i class="fa fa-check"></i><b>15.2.2</b> Family 2</a></li>
<li class="chapter" data-level="15.2.3" data-path="d-linear-transformations.html"><a href="d-linear-transformations.html#family-3"><i class="fa fa-check"></i><b>15.2.3</b> Family 3</a></li>
<li class="chapter" data-level="15.2.4" data-path="d-linear-transformations.html"><a href="d-linear-transformations.html#family-4"><i class="fa fa-check"></i><b>15.2.4</b> Family 4</a></li>
<li class="chapter" data-level="15.2.5" data-path="d-linear-transformations.html"><a href="d-linear-transformations.html#some-other-matrices"><i class="fa fa-check"></i><b>15.2.5</b> Some Other Matrices</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="d-linear-transformations.html"><a href="d-linear-transformations.html#exploration"><i class="fa fa-check"></i><b>15.3</b> Exploration</a></li>
<li class="chapter" data-level="15.4" data-path="d-linear-transformations.html"><a href="d-linear-transformations.html#even-more-exploration"><i class="fa fa-check"></i><b>15.4</b> Even More Exploration</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="linear-transformations-of-a-house.html"><a href="linear-transformations-of-a-house.html"><i class="fa fa-check"></i><b>16</b> Linear Transformations of a House</a><ul>
<li class="chapter" data-level="16.1" data-path="linear-transformations-of-a-house.html"><a href="linear-transformations-of-a-house.html#rotations"><i class="fa fa-check"></i><b>16.1</b> Rotations</a><ul>
<li class="chapter" data-level="16.1.1" data-path="linear-transformations-of-a-house.html"><a href="linear-transformations-of-a-house.html#your-turn-1"><i class="fa fa-check"></i><b>16.1.1</b> Your Turn</a></li>
</ul></li>
<li class="chapter" data-level="16.2" data-path="linear-transformations-of-a-house.html"><a href="linear-transformations-of-a-house.html#expansion-and-contraction"><i class="fa fa-check"></i><b>16.2</b> Expansion and contraction</a><ul>
<li class="chapter" data-level="16.2.1" data-path="linear-transformations-of-a-house.html"><a href="linear-transformations-of-a-house.html#your-turn-2"><i class="fa fa-check"></i><b>16.2.1</b> Your Turn</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="linear-transformations-of-a-house.html"><a href="linear-transformations-of-a-house.html#reflection-over-the-line-yx"><i class="fa fa-check"></i><b>16.3</b> Reflection over the line <span class="math inline">\(y=x\)</span></a><ul>
<li class="chapter" data-level="16.3.1" data-path="linear-transformations-of-a-house.html"><a href="linear-transformations-of-a-house.html#your-turn-3"><i class="fa fa-check"></i><b>16.3.1</b> Your Turn</a></li>
</ul></li>
<li class="chapter" data-level="16.4" data-path="linear-transformations-of-a-house.html"><a href="linear-transformations-of-a-house.html#shear-transformations"><i class="fa fa-check"></i><b>16.4</b> Shear Transformations</a><ul>
<li class="chapter" data-level="16.4.1" data-path="linear-transformations-of-a-house.html"><a href="linear-transformations-of-a-house.html#your-turn-4"><i class="fa fa-check"></i><b>16.4.1</b> Your Turn</a></li>
</ul></li>
<li class="chapter" data-level="16.5" data-path="linear-transformations-of-a-house.html"><a href="linear-transformations-of-a-house.html#dimension-reduction"><i class="fa fa-check"></i><b>16.5</b> Dimension Reduction</a><ul>
<li class="chapter" data-level="16.5.1" data-path="linear-transformations-of-a-house.html"><a href="linear-transformations-of-a-house.html#your-turn-5"><i class="fa fa-check"></i><b>16.5.1</b> Your Turn</a></li>
</ul></li>
<li class="chapter" data-level="16.6" data-path="linear-transformations-of-a-house.html"><a href="linear-transformations-of-a-house.html#a-complicated-transformation"><i class="fa fa-check"></i><b>16.6</b> A Complicated Transformation</a><ul>
<li class="chapter" data-level="16.6.1" data-path="linear-transformations-of-a-house.html"><a href="linear-transformations-of-a-house.html#your-turn-6"><i class="fa fa-check"></i><b>16.6.1</b> Your Turn</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="d-translations-with-homogeneous-coordinates.html"><a href="d-translations-with-homogeneous-coordinates.html"><i class="fa fa-check"></i><b>17</b> 2D Translations with Homogeneous Coordinates</a><ul>
<li class="chapter" data-level="17.1" data-path="d-translations-with-homogeneous-coordinates.html"><a href="d-translations-with-homogeneous-coordinates.html#translation"><i class="fa fa-check"></i><b>17.1</b> Translation</a></li>
<li class="chapter" data-level="17.2" data-path="d-translations-with-homogeneous-coordinates.html"><a href="d-translations-with-homogeneous-coordinates.html#translation-and-then-rotation"><i class="fa fa-check"></i><b>17.2</b> Translation and then Rotation</a></li>
<li class="chapter" data-level="17.3" data-path="d-translations-with-homogeneous-coordinates.html"><a href="d-translations-with-homogeneous-coordinates.html#rotation-and-then-translation"><i class="fa fa-check"></i><b>17.3</b> Rotation and then Translation</a></li>
<li class="chapter" data-level="17.4" data-path="d-translations-with-homogeneous-coordinates.html"><a href="d-translations-with-homogeneous-coordinates.html#your-turn-7"><i class="fa fa-check"></i><b>17.4</b> Your Turn</a><ul>
<li class="chapter" data-level="17.4.1" data-path="d-translations-with-homogeneous-coordinates.html"><a href="d-translations-with-homogeneous-coordinates.html#house-of-orange"><i class="fa fa-check"></i><b>17.4.1</b> House of Orange</a></li>
<li class="chapter" data-level="17.4.2" data-path="d-translations-with-homogeneous-coordinates.html"><a href="d-translations-with-homogeneous-coordinates.html#house-party"><i class="fa fa-check"></i><b>17.4.2</b> House Party</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="18" data-path="fractals.html"><a href="fractals.html"><i class="fa fa-check"></i><b>18</b> Fractals</a><ul>
<li class="chapter" data-level="18.1" data-path="fractals.html"><a href="fractals.html#transforming-my-house."><i class="fa fa-check"></i><b>18.1</b> Transforming My House.</a></li>
<li class="chapter" data-level="18.2" data-path="fractals.html"><a href="fractals.html#watching-a-series-of-points."><i class="fa fa-check"></i><b>18.2</b> Watching a series of points.</a></li>
<li class="chapter" data-level="18.3" data-path="fractals.html"><a href="fractals.html#here-are-some-from-httppaulbourke.netfractalsifs"><i class="fa fa-check"></i><b>18.3</b> Here are some from <span>http://paulbourke.net/fractals/ifs/</span></a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="dynamical-systems-in-2d.html"><a href="dynamical-systems-in-2d.html"><i class="fa fa-check"></i><b>19</b> Dynamical Systems in 2D</a><ul>
<li class="chapter" data-level="19.1" data-path="dynamical-systems-in-2d.html"><a href="dynamical-systems-in-2d.html#helper-function-to-plot-dynamical-systems"><i class="fa fa-check"></i><b>19.1</b> Helper Function to Plot Dynamical Systems</a></li>
<li class="chapter" data-level="19.2" data-path="dynamical-systems-in-2d.html"><a href="dynamical-systems-in-2d.html#our-first-example"><i class="fa fa-check"></i><b>19.2</b> Our first example</a></li>
<li class="chapter" data-level="19.3" data-path="dynamical-systems-in-2d.html"><a href="dynamical-systems-in-2d.html#your-turn-8"><i class="fa fa-check"></i><b>19.3</b> Your Turn</a><ul>
<li class="chapter" data-level="19.3.1" data-path="dynamical-systems-in-2d.html"><a href="dynamical-systems-in-2d.html#example-1"><i class="fa fa-check"></i><b>19.3.1</b> Example 1</a></li>
<li class="chapter" data-level="19.3.2" data-path="dynamical-systems-in-2d.html"><a href="dynamical-systems-in-2d.html#example-2"><i class="fa fa-check"></i><b>19.3.2</b> Example 2</a></li>
<li class="chapter" data-level="19.3.3" data-path="dynamical-systems-in-2d.html"><a href="dynamical-systems-in-2d.html#example-3"><i class="fa fa-check"></i><b>19.3.3</b> Example 3</a></li>
<li class="chapter" data-level="19.3.4" data-path="dynamical-systems-in-2d.html"><a href="dynamical-systems-in-2d.html#example-4"><i class="fa fa-check"></i><b>19.3.4</b> Example 4</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="20" data-path="network-centralities.html"><a href="network-centralities.html"><i class="fa fa-check"></i><b>20</b> Network Centralities</a><ul>
<li class="chapter" data-level="20.1" data-path="network-centralities.html"><a href="network-centralities.html#graphs-and-networks"><i class="fa fa-check"></i><b>20.1</b> Graphs and Networks</a><ul>
<li class="chapter" data-level="20.1.1" data-path="network-centralities.html"><a href="network-centralities.html#adjacency-matrices"><i class="fa fa-check"></i><b>20.1.1</b> Adjacency Matrices</a></li>
<li class="chapter" data-level="20.1.2" data-path="network-centralities.html"><a href="network-centralities.html#graph-layouts"><i class="fa fa-check"></i><b>20.1.2</b> Graph Layouts</a></li>
</ul></li>
<li class="chapter" data-level="20.2" data-path="network-centralities.html"><a href="network-centralities.html#degree-centrality"><i class="fa fa-check"></i><b>20.2</b> Degree Centrality</a></li>
<li class="chapter" data-level="20.3" data-path="network-centralities.html"><a href="network-centralities.html#goulds-index"><i class="fa fa-check"></i><b>20.3</b> Gould’s Index</a><ul>
<li class="chapter" data-level="20.3.1" data-path="network-centralities.html"><a href="network-centralities.html#step-1"><i class="fa fa-check"></i><b>20.3.1</b> Step 1</a></li>
<li class="chapter" data-level="20.3.2" data-path="network-centralities.html"><a href="network-centralities.html#step-2"><i class="fa fa-check"></i><b>20.3.2</b> Step 2</a></li>
<li class="chapter" data-level="20.3.3" data-path="network-centralities.html"><a href="network-centralities.html#step-3"><i class="fa fa-check"></i><b>20.3.3</b> Step 3</a></li>
<li class="chapter" data-level="20.3.4" data-path="network-centralities.html"><a href="network-centralities.html#step-4"><i class="fa fa-check"></i><b>20.3.4</b> Step 4</a></li>
<li class="chapter" data-level="20.3.5" data-path="network-centralities.html"><a href="network-centralities.html#step-5"><i class="fa fa-check"></i><b>20.3.5</b> Step 5</a></li>
<li class="chapter" data-level="20.3.6" data-path="network-centralities.html"><a href="network-centralities.html#gould-index-summary"><i class="fa fa-check"></i><b>20.3.6</b> Gould Index Summary</a></li>
</ul></li>
<li class="chapter" data-level="20.4" data-path="network-centralities.html"><a href="network-centralities.html#your-turn-the-rise-of-moscow"><i class="fa fa-check"></i><b>20.4</b> Your Turn: The Rise of Moscow</a><ul>
<li class="chapter" data-level="20.4.1" data-path="network-centralities.html"><a href="network-centralities.html#find-the-degree-centrality-values."><i class="fa fa-check"></i><b>20.4.1</b> Find the Degree Centrality values.</a></li>
<li class="chapter" data-level="20.4.2" data-path="network-centralities.html"><a href="network-centralities.html#find-the-gould-index-values"><i class="fa fa-check"></i><b>20.4.2</b> Find the Gould Index values</a></li>
<li class="chapter" data-level="20.4.3" data-path="network-centralities.html"><a href="network-centralities.html#analyze-the-data"><i class="fa fa-check"></i><b>20.4.3</b> Analyze the Data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="21" data-path="voting-patterns-in-the-us-senate.html"><a href="voting-patterns-in-the-us-senate.html"><i class="fa fa-check"></i><b>21</b> Voting Patterns in the US Senate</a><ul>
<li class="chapter" data-level="21.1" data-path="voting-patterns-in-the-us-senate.html"><a href="voting-patterns-in-the-us-senate.html#the-data"><i class="fa fa-check"></i><b>21.1</b> The Data</a></li>
<li class="chapter" data-level="21.2" data-path="voting-patterns-in-the-us-senate.html"><a href="voting-patterns-in-the-us-senate.html#the-88th-congressional-session-1964"><i class="fa fa-check"></i><b>21.2</b> The 88th Congressional Session (1964)</a></li>
<li class="chapter" data-level="21.3" data-path="voting-patterns-in-the-us-senate.html"><a href="voting-patterns-in-the-us-senate.html#using-the-eigenbasis"><i class="fa fa-check"></i><b>21.3</b> Using the Eigenbasis</a><ul>
<li class="chapter" data-level="21.3.1" data-path="voting-patterns-in-the-us-senate.html"><a href="voting-patterns-in-the-us-senate.html#using-the-dominant-eigenvectors."><i class="fa fa-check"></i><b>21.3.1</b> Using the Dominant Eigenvectors.</a></li>
<li class="chapter" data-level="21.3.2" data-path="voting-patterns-in-the-us-senate.html"><a href="voting-patterns-in-the-us-senate.html#patterns-in-the-first-two-eigenvectors"><i class="fa fa-check"></i><b>21.3.2</b> Patterns in the First Two Eigenvectors</a></li>
<li class="chapter" data-level="21.3.3" data-path="voting-patterns-in-the-us-senate.html"><a href="voting-patterns-in-the-us-senate.html#creating-a-table-sorted-by-an-eigenvector"><i class="fa fa-check"></i><b>21.3.3</b> Creating a Table Sorted by an Eigenvector</a></li>
</ul></li>
<li class="chapter" data-level="21.4" data-path="voting-patterns-in-the-us-senate.html"><a href="voting-patterns-in-the-us-senate.html#your-turn-12"><i class="fa fa-check"></i><b>21.4</b> Your Turn</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="modeling-of-ecological-systems.html"><a href="modeling-of-ecological-systems.html"><i class="fa fa-check"></i><b>22</b> Modeling of Ecological Systems</a><ul>
<li class="chapter" data-level="22.1" data-path="modeling-of-ecological-systems.html"><a href="modeling-of-ecological-systems.html#helper-functions-to-plot-dynamical-systems"><i class="fa fa-check"></i><b>22.1</b> Helper Functions to Plot Dynamical Systems</a></li>
<li class="chapter" data-level="22.2" data-path="modeling-of-ecological-systems.html"><a href="modeling-of-ecological-systems.html#northern-spotted-owl-population"><i class="fa fa-check"></i><b>22.2</b> Northern Spotted Owl Population</a><ul>
<li class="chapter" data-level="22.2.1" data-path="modeling-of-ecological-systems.html"><a href="modeling-of-ecological-systems.html#population-forecast"><i class="fa fa-check"></i><b>22.2.1</b> Population forecast</a></li>
<li class="chapter" data-level="22.2.2" data-path="modeling-of-ecological-systems.html"><a href="modeling-of-ecological-systems.html#the-population-at-t200"><i class="fa fa-check"></i><b>22.2.2</b> The population at <span class="math inline">\(t=200\)</span></a></li>
<li class="chapter" data-level="22.2.3" data-path="modeling-of-ecological-systems.html"><a href="modeling-of-ecological-systems.html#eigenvectors-and-eigenvalues-of-l"><i class="fa fa-check"></i><b>22.2.3</b> Eigenvectors and eigenvalues of <span class="math inline">\(L\)</span></a></li>
</ul></li>
<li class="chapter" data-level="22.3" data-path="modeling-of-ecological-systems.html"><a href="modeling-of-ecological-systems.html#northern-spotted-owls-revisited"><i class="fa fa-check"></i><b>22.3</b> Northern Spotted Owls Revisited</a><ul>
<li class="chapter" data-level="22.3.1" data-path="modeling-of-ecological-systems.html"><a href="modeling-of-ecological-systems.html#find-the-long-range-populations"><i class="fa fa-check"></i><b>22.3.1</b> Find the long-range populations</a></li>
<li class="chapter" data-level="22.3.2" data-path="modeling-of-ecological-systems.html"><a href="modeling-of-ecological-systems.html#the-populations-at-t100-versus-the-dominant-eigenvector"><i class="fa fa-check"></i><b>22.3.2</b> The populations at <span class="math inline">\(t=100\)</span> versus the dominant eigenvector</a></li>
<li class="chapter" data-level="22.3.3" data-path="modeling-of-ecological-systems.html"><a href="modeling-of-ecological-systems.html#the-long-range-prospects"><i class="fa fa-check"></i><b>22.3.3</b> The long-range prospects</a></li>
</ul></li>
<li class="chapter" data-level="22.4" data-path="modeling-of-ecological-systems.html"><a href="modeling-of-ecological-systems.html#brook-trout-in-hunt-creek-mi"><i class="fa fa-check"></i><b>22.4</b> Brook Trout in Hunt Creek, MI</a><ul>
<li class="chapter" data-level="22.4.1" data-path="modeling-of-ecological-systems.html"><a href="modeling-of-ecological-systems.html#the-leslie-matrix"><i class="fa fa-check"></i><b>22.4.1</b> The Leslie Matrix</a></li>
<li class="chapter" data-level="22.4.2" data-path="modeling-of-ecological-systems.html"><a href="modeling-of-ecological-systems.html#find-the-long-range-populations-1"><i class="fa fa-check"></i><b>22.4.2</b> Find the long-range populations</a></li>
<li class="chapter" data-level="22.4.3" data-path="modeling-of-ecological-systems.html"><a href="modeling-of-ecological-systems.html#river-clean-up"><i class="fa fa-check"></i><b>22.4.3</b> River Clean Up</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="23" data-path="digit-recognition.html"><a href="digit-recognition.html"><i class="fa fa-check"></i><b>23</b> Digit Recognition</a><ul>
<li class="chapter" data-level="23.1" data-path="digit-recognition.html"><a href="digit-recognition.html#us-post-office-zip-code-data"><i class="fa fa-check"></i><b>23.1</b> US Post Office Zip Code Data</a><ul>
<li class="chapter" data-level="23.1.1" data-path="digit-recognition.html"><a href="digit-recognition.html#visualizing-the-data"><i class="fa fa-check"></i><b>23.1.1</b> Visualizing the Data</a></li>
<li class="chapter" data-level="23.1.2" data-path="digit-recognition.html"><a href="digit-recognition.html#algorithm-overview"><i class="fa fa-check"></i><b>23.1.2</b> Algorithm Overview</a></li>
</ul></li>
<li class="chapter" data-level="23.2" data-path="digit-recognition.html"><a href="digit-recognition.html#length-distance-and-angle"><i class="fa fa-check"></i><b>23.2</b> Length, Distance and Angle</a></li>
<li class="chapter" data-level="23.3" data-path="digit-recognition.html"><a href="digit-recognition.html#machine-learning-algorithms"><i class="fa fa-check"></i><b>23.3</b> Machine Learning Algorithms</a><ul>
<li class="chapter" data-level="23.3.1" data-path="digit-recognition.html"><a href="digit-recognition.html#get-closest-by-distance"><i class="fa fa-check"></i><b>23.3.1</b> Get Closest by Distance</a></li>
<li class="chapter" data-level="23.3.2" data-path="digit-recognition.html"><a href="digit-recognition.html#get-closest-by-angle"><i class="fa fa-check"></i><b>23.3.2</b> Get Closest by Angle</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>IV Quiz Review</b></span></li>
<li class="chapter" data-level="24" data-path="quiz-1-review.html"><a href="quiz-1-review.html"><i class="fa fa-check"></i><b>24</b> Quiz 1 Review</a><ul>
<li class="chapter" data-level="24.1" data-path="quiz-1-review.html"><a href="quiz-1-review.html#overview"><i class="fa fa-check"></i><b>24.1</b> Overview</a><ul>
<li class="chapter" data-level="24.1.1" data-path="quiz-1-review.html"><a href="quiz-1-review.html#vocabulary-and-concepts"><i class="fa fa-check"></i><b>24.1.1</b> Vocabulary and Concepts</a></li>
<li class="chapter" data-level="24.1.2" data-path="quiz-1-review.html"><a href="quiz-1-review.html#skills"><i class="fa fa-check"></i><b>24.1.2</b> Skills</a></li>
</ul></li>
<li class="chapter" data-level="24.2" data-path="quiz-1-review.html"><a href="quiz-1-review.html#practice-problems"><i class="fa fa-check"></i><b>24.2</b> Practice Problems</a></li>
<li class="chapter" data-level="24.3" data-path="quiz-1-review.html"><a href="quiz-1-review.html#solutions-to-practice-problems"><i class="fa fa-check"></i><b>24.3</b> Solutions to Practice Problems</a></li>
</ul></li>
<li class="chapter" data-level="25" data-path="quiz-2-review.html"><a href="quiz-2-review.html"><i class="fa fa-check"></i><b>25</b> Quiz 2 Review</a><ul>
<li class="chapter" data-level="25.1" data-path="quiz-2-review.html"><a href="quiz-2-review.html#overview-1"><i class="fa fa-check"></i><b>25.1</b> Overview</a><ul>
<li class="chapter" data-level="25.1.1" data-path="quiz-2-review.html"><a href="quiz-2-review.html#vocabulary-and-concepts-1"><i class="fa fa-check"></i><b>25.1.1</b> Vocabulary and Concepts</a></li>
<li class="chapter" data-level="25.1.2" data-path="quiz-2-review.html"><a href="quiz-2-review.html#skills-1"><i class="fa fa-check"></i><b>25.1.2</b> Skills</a></li>
</ul></li>
<li class="chapter" data-level="25.2" data-path="quiz-2-review.html"><a href="quiz-2-review.html#practice-problems-1"><i class="fa fa-check"></i><b>25.2</b> Practice Problems</a></li>
<li class="chapter" data-level="25.3" data-path="quiz-2-review.html"><a href="quiz-2-review.html#solutions-to-practice-problems-1"><i class="fa fa-check"></i><b>25.3</b> Solutions to Practice Problems</a></li>
</ul></li>
<li class="chapter" data-level="26" data-path="quiz-3-review.html"><a href="quiz-3-review.html"><i class="fa fa-check"></i><b>26</b> Quiz 3 Review</a><ul>
<li class="chapter" data-level="26.1" data-path="quiz-3-review.html"><a href="quiz-3-review.html#overview-2"><i class="fa fa-check"></i><b>26.1</b> Overview</a><ul>
<li class="chapter" data-level="26.1.1" data-path="quiz-3-review.html"><a href="quiz-3-review.html#vocabulary-concepts-and-skills"><i class="fa fa-check"></i><b>26.1.1</b> Vocabulary, Concepts and Skills</a></li>
</ul></li>
<li class="chapter" data-level="26.2" data-path="quiz-3-review.html"><a href="quiz-3-review.html#practice-problems-2"><i class="fa fa-check"></i><b>26.2</b> Practice Problems</a></li>
<li class="chapter" data-level="26.3" data-path="quiz-3-review.html"><a href="quiz-3-review.html#solutions-to-practice-problems-2"><i class="fa fa-check"></i><b>26.3</b> Solutions to Practice Problems</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">MATH 236: Linear Algebra</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="quiz-3-review" class="section level1">
<h1><span class="header-section-number">Vector 26</span> Quiz 3 Review</h1>
<div id="overview-2" class="section level2">
<h2><span class="header-section-number">26.1</span> Overview</h2>
<p>Our third quiz covers sections 5.1-5.3 and 5.5-5.6 in Lay’s book. This corresponds to Problem Sets 6 and 7.</p>
<p>The best way to study is to do practice problems. The Quiz will have calculation problems (like Edfinity) and more conceptual problems (like the problem sets). Here are some ways to practice:</p>
<ul>
<li>Make sure that you have mastered the Vocabulary, Skills and Concepts listed below.</li>
<li>Look over the Edfinity homework assingments</li>
<li>Do practice problems from the Edfinity Practice assignments. These allow you to “Practice Similar” by generating new variations of the same problem.</li>
<li>Try to resolve the Problem Sets and compare your answers to the solutions.</li>
<li>Do the practice problems below. Compare your answers to the solutions.</li>
</ul>
<div id="vocabulary-concepts-and-skills" class="section level3">
<h3><span class="header-section-number">26.1.1</span> Vocabulary, Concepts and Skills</h3>
<p>See the <a href="week-5-6-learning-goals">Week 5-6 Learning Goals</a> for the list of vocabulary, concepts and skills.</p>
</div>
</div>
<div id="practice-problems-2" class="section level2">
<h2><span class="header-section-number">26.2</span> Practice Problems</h2>
<ol style="list-style-type: decimal">
<li><p>Consider the <span class="math inline">\(3 \times 3\)</span> matrix
<span class="math display">\[
A = 
\left[
\begin{array}{rrr}
2 &amp; -1 &amp; 0 \\
0 &amp; 1 &amp; 0 \\
-2 &amp; 5 &amp; -2 \\
\end{array}
\right]
\]</span>
with characteristic equation
<span class="math display">\[
p(\lambda) = -(\lambda -1)(\lambda -2)(\lambda +2).
\]</span>
Find the eigenvalues and corresponding eigenvectors for <span class="math inline">\(A\)</span>.</p></li>
<li><p>Let <span class="math inline">\(A\)</span> be a <span class="math inline">\(2 \times 2\)</span> matrix. We view <span class="math inline">\(A\)</span> as a linear transformation from <span class="math inline">\(\mathbb{R}^2\)</span> to <span class="math inline">\(\mathbb{R}^2\)</span>. Describe the eigenvalues for each of the following types of matrices.</p>
<ol style="list-style-type: lower-alpha">
<li><span class="math inline">\(A\)</span> maps <span class="math inline">\(\mathbb{R}^2\)</span> onto a line through the origin in <span class="math inline">\(\mathbb{R}^2\)</span>.</li>
<li><span class="math inline">\(A\)</span> is a reflection of <span class="math inline">\(\mathbb{R}^2\)</span> about a line through the origin</li>
<li><span class="math inline">\(A\)</span> is a reflection of <span class="math inline">\(\mathbb{R}^2\)</span> through the origin</li>
<li><span class="math inline">\(A\)</span> is a horizontal shear</li>
</ol></li>
<li><p>Below are the eigenvalues of four different <span class="math inline">\(5 \times 5\)</span> matrices. For each, decide if the matrix is invertible and if it is diagonalizable.
Answer Yes, No or “Not enough information to determine this.”</p>
<ol style="list-style-type: lower-alpha">
<li><span class="math inline">\(A\)</span> has eigenvalues <span class="math inline">\(\lambda = -4, -3,0,1, 2\)</span></li>
<li><span class="math inline">\(B\)</span> has eigenvalues <span class="math inline">\(\lambda = -3, -1, 1, \sqrt{2}, 8.\)</span></li>
<li><span class="math inline">\(C\)</span> has eigenvalues <span class="math inline">\(\lambda = 1, 2, 2, 7, 8.\)</span></li>
<li><span class="math inline">\(D\)</span> has eigenvalues <span class="math inline">\(\lambda = -1, 0, 3,3, 10\)</span></li>
</ol></li>
<li><p>Here the diagonalization of a matrix:
<span class="math display">\[
 \mathsf{A}=\left[
\begin{array}{ccc}
 5 &amp; 2 &amp; -1 \\
 2 &amp; 1 &amp; 0 \\
 -1 &amp; 0 &amp; 1 \\
\end{array}
\right] = 
\left[
\begin{array}{ccc}
 -5 &amp; 0 &amp; 1 \\
 -2 &amp; 1 &amp; -2 \\
 1 &amp; 2 &amp; 1 \\
\end{array}
\right] \left[
\begin{array}{ccc}
 6 &amp; 0 &amp; 0 \\
 0 &amp; 1 &amp; 0 \\
 0 &amp; 0 &amp; 0 \\
\end{array}
\right]\left[
\begin{array}{ccc}
 -\frac{1}{6} &amp; -\frac{1}{15} &amp; \frac{1}{30} \\
 0 &amp; \frac{1}{5} &amp; \frac{2}{5} \\
 \frac{1}{6} &amp; -\frac{1}{3} &amp; \frac{1}{6} \\
\end{array}
\right].
\]</span></p>
<ol style="list-style-type: lower-alpha">
<li>Is the matrix <span class="math inline">\(\mathsf{A}\)</span> invertible?</li>
<li>Find a nonzero vector in <span class="math inline">\(\mathrm{Nul}(\mathsf{A})\)</span> if one exists.</li>
<li>Find a steady-state vector <span class="math inline">\(\mathsf{v}\)</span> such that <span class="math inline">\(\mathsf{A} \mathsf{v} = \mathsf{v}\)</span> if one exists.</li>
<li>Give the coordinates of <span class="math inline">\(\mathsf{v} = [1,2,3]^T\)</span> in the eigenbasis without row reductions.</li>
<li>Find a formula for <span class="math inline">\(\mathsf{A}^{2020} \mathsf{v}\)</span> if <span class="math inline">\(\mathsf{v} = [1,2,3]^T\)</span> in terms of the eigenbasis.</li>
</ol></li>
<li><p>The eigensystem of matrix <span class="math inline">\(A\)</span> is given below. It has complex eigenvalues. What angle does it rotate by? What factor does it scale by?
<span class="math display">\[
\begin{bmatrix} 3 &amp; -5 \\ 1 &amp; -1 \end{bmatrix}, \qquad
\lambda = 1 \pm i,
\qquad
v = \begin{bmatrix} 2 \\ 1 \end{bmatrix} \pm \begin{bmatrix} 1 \\ 0 \end{bmatrix} i.
\]</span></p></li>
<li><p>Using the matrix <span class="math inline">\(B = = \begin{bmatrix} .97 &amp; -.71 \\ .71 &amp; .97 \end{bmatrix}\)</span> and the starting vector <span class="math inline">\(\mathsf{v} = \begin{bmatrix} 1 \\ 0 \end{bmatrix}\)</span>, I plotted the points
<span class="math display">\[\mathsf{v}, B \mathsf{v}, B^2\mathsf{v}, B^3 \mathsf{v}, \ldots.\]</span>
I saw that these points are, roughly, going around in a circle.</p>
<ol style="list-style-type: lower-alpha">
<li>How many multiplications by <span class="math inline">\(B\)</span> does it take to get back around to the positive <span class="math inline">\(x\)</span>-axis?<br />
</li>
<li>When I come full circle, am I closer to the origin, farther from the origin, or the same distance to the origin?</li>
</ol></li>
<li><p>For each matrix below, decide if it is diagonalizable. You do not need to diagonalize the matrix (though you can!), but you must give a reason for why the matrix is or is not diagonalizable.</p>
<ol style="list-style-type: lower-alpha">
<li><p><span class="math inline">\(A = \begin{bmatrix} 0 &amp; -4 &amp; 2 \\ 2 &amp; -4 &amp; -1 \\ -6 &amp; 4 &amp; 7 \end{bmatrix}\)</span> has eigenvalues <span class="math inline">\(4, -1, 0\)</span>.</p></li>
<li><p><span class="math inline">\(B = \begin{bmatrix} 3 &amp; -1 &amp; 2 \\ -1 &amp; 3 &amp; 2 \\ 2&amp;2 &amp; 0 \end{bmatrix}\)</span> has eigenvalues <span class="math inline">\(4,4,-2\)</span>.</p></li>
</ol></li>
<li><p>Consider the matrix with eigenvalues and eigenvectors
<span class="math display">\[
A = \begin{bmatrix} 0.7 &amp; 0.2 \\ 0.3 &amp; 0.8 \end{bmatrix}
\qquad
\begin{array}{cc}
\lambda_1 = 1  &amp; \lambda_2 = .5 \\
\mathsf{v}_1 = \begin{bmatrix} 2 \\ 3 \end{bmatrix} &amp; \mathsf{v}_2 = \begin{bmatrix} 1 \\ -1 \end{bmatrix} 
\end{array}
\]</span></p>
<ol style="list-style-type: lower-alpha">
<li>Diagonalize <span class="math inline">\(A\)</span>.</li>
<li>What can you say about <span class="math inline">\(\displaystyle{\lim_{n \to \infty}} A^n\)</span>?</li>
<li>Give a formula for <span class="math inline">\(A^n \mathsf{x}_0\)</span> if <span class="math inline">\(\mathsf{x}_0 = \begin{bmatrix} 25 \\ 0 \end{bmatrix}\)</span> in terms of the eigenbasis.</li>
<li>What is <span class="math inline">\(\displaystyle{\lim_{n \to \infty}} A^n \begin{bmatrix} 25 \\ 0 \end{bmatrix}\)</span>?</li>
</ol></li>
<li><p>The matrix <span class="math inline">\(A\)</span> below has the given eigenvalues and eigenvectors.
<span class="math display">\[
A = \left[
\begin{array}{cc}
 \frac{1}{2} &amp; \frac{1}{5} \\
 -\frac{2}{5} &amp; \frac{9}{10} \\
\end{array}
\right]
\qquad
\begin{array}{c}
\lambda = .7  \pm .2 i \\
\mathsf{v} = \begin{bmatrix} \frac{1}{2} \\ 1 \end{bmatrix} \pm   \begin{bmatrix} -\frac{1}{2} \\ 0 \end{bmatrix} i
\end{array}\hskip5in
\]</span></p>
<ol style="list-style-type: lower-alpha">
<li>Factor <span class="math inline">\(A=PCP^{-1}\)</span> where <span class="math inline">\(C\)</span> is a rotation-scaling matrix.</li>
<li>What is the angle of rotation?</li>
<li>What is the factor of dilation?</li>
</ol></li>
<li><p>In a 1962 study of rainfall in Tel Aviv, it was determined that if today is a wet day, then the probability that tomorrow will be wet is 0.662 and the probability that tomorrow it will be dry is 0.338. If today is a dry day, then the probability that tomorrow is wet is 0.250 and the probability that tomorrow is dry will be 0.75. From this I computed the following:
<span class="math display">\[
A = \begin{bmatrix} 0.662 &amp; 0.25 \\ 0.338 &amp; 0.75\end{bmatrix};
\qquad
\begin{array}{cc}
 \lambda_1 = 1.0 &amp; \lambda_2 = 0.412 \\
 \mathsf{v}_1 = \begin{bmatrix}-0.595 \\ -0.804 \end{bmatrix} &amp; \quad \mathsf{v}_2 = \begin{bmatrix}-0.707\\ 0.707 \end{bmatrix}
 \end{array}
\]</span></p>
<ol style="list-style-type: lower-alpha">
<li>If Monday is a dry day, what is the probability that Wednesday will be wet?</li>
<li>In the long-run, what is the distribution of wet and dry days?</li>
</ol></li>
<li><p>Conservation biologists in the Minnesota boundary waters have modeled the predator-prey dynamics of Grey Wolves <span class="math inline">\(X\)</span> and White Tailed Deer <span class="math inline">\(Y\)</span>, which have a predator-prey relationship:
<span class="math display">\[
\left[ 
\begin{array}{r} 
X_{t+1} \\ Y_{t+1} 
\end{array}
\right]
=
\left[ 
\begin{array}{rr} 
0.7 &amp; 0.4 \\
-0.2 &amp; 1.2
\end{array}
\right]
\left[ 
\begin{array}{r} 
X_{t} \\ Y_{t} 
\end{array}
\right]
\qquad \mbox{where} \qquad
X_0=1 \mbox{ and } Y_0=2. 
\]</span>
Here, <span class="math inline">\(t\)</span> is measured in years and <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are measured in <span class="math inline">\(100,000\)</span> animals.</p>
<ol style="list-style-type: lower-alpha">
<li><p>The plot below shows the vector field for this dynamical system. Draw or describe the trajectory of the populations starting at <span class="math inline">\([X_0, Y_0] = [1,2]\)</span>. In one or two sentences, describe what happens to these populations over time.</p>
<center>
<p><img src="images/q3-wolfdeer1.png" style="width:60.0%" /></p>
</center></li>
<li><p>The population biologists consider two options to fix this system. The first option is a <strong>deer breeding program</strong> to increase their productivity. Their adjusted model becomes:
<span class="math display">\[
\left[ 
\begin{array}{r} 
X_{t+1} \\ Y_{t+1} 
\end{array}
\right]
=
\left[ 
\begin{array}{rr} 
0.7 &amp; 0.4 \\
-0.2 &amp; 1.3
\end{array}
\right]
\left[ 
\begin{array}{r} 
X_{t} \\ Y_{t} 
\end{array}
\right]
\]</span>
whose transition matrix has eigenvectors and eigenvalues
<span class="math display">\[
\lambda_1 = 1.1  \mbox{ with eigenvector }  \begin{bmatrix} 1 \\ 1 \end{bmatrix} 
\quad \mbox{and} \quad
\lambda_2 = 0.9  \mbox{ with eigenvector }   \begin{bmatrix} 1 \\ 0.5 \end{bmatrix}. 
\]</span></p>
<center>
<p><img src="images/q3-wolfdeer2.png" style="width:60.0%" /></p>
</center>
<p>Draw or describe the trajectory of the populations starting at <span class="math inline">\((X_0, Y_0) = (1,2)\)</span> in the above vector plot. Describe what happens to these populations over time, and relate these observations to the eigenvectors and eigenvalues of the transition matrix.</p></li>
<li><p>The second option they consider is a <strong>limited wolf hunting season</strong>. This reduces the productivity of the wolves, giving the new model:
<span class="math display">\[
\left[ 
\begin{array}{r} 
X_{t+1} \\ Y_{t+1} 
\end{array}
\right]
=
\left[ 
\begin{array}{rr} 
0.6 &amp; 0.4 \\
-0.2 &amp; 1.2
\end{array}
\right]
\left[ 
\begin{array}{r} 
X_{t} \\ Y_{t} 
\end{array}
\right]
\]</span>
whose transition matrix has eigenvectors and eigenvalues
<span class="math display">\[
\lambda_1 = 1  \mbox{ with eigenvector }  \begin{bmatrix} 1 \\ 1 \end{bmatrix}  \quad \mbox{and} \quad
\lambda_2 = 0.8 \mbox{ with eigenvector }   \begin{bmatrix} 1 \\ 0.5 \end{bmatrix} 
\]</span></p>
<center>
<p><img src="images/q3-wolfdeer3.png" style="width:60.0%" /></p>
</center>
<p>Once again, draw or desctibe the trajectory of the populations starting at <span class="math inline">\((X_0, Y_0) = (1,2)\)</span> in the above vector plot. Describe what happens to these populations over time, and relate these observations to the eigenvectors and eigenvalues of the transition matrix.</p></li>
<li><p>The conservation biologists want to create a stable ecosystem, where the populations of deer and wolves remain constant over time. Which option (deer breeding or limited wolf hunting) would you recommend?</p></li>
</ol></li>
<li><p>A population of female bison is split into three groups: juveniles who are
less than one year old; yearlings between one and two years old; and adults who
are older than two years. Each year,</p>
<ul>
<li>80% of the juveniles survive to become yearlings.</li>
<li>90% of the yearlings survive to become adults.</li>
<li>80% of the adults survive.</li>
<li>40% of the adults give birth to a juvenile
Let
<span class="math inline">\(\mathsf{x}_t = \begin{bmatrix} J_t \\ Y_t \\ A_t \end{bmatrix}\)</span> be the
state of the system in year <span class="math inline">\(t\)</span>.</li>
</ul>
<ol style="list-style-type: lower-alpha">
<li>Find the Leslie matrix <span class="math inline">\(L\)</span> such that <span class="math inline">\(\mathsf{x}_{t+1} = B \mathsf{x}_t.\)</span>.</li>
<li>Find the eigenvalues of <span class="math inline">\(L\)</span>.</li>
<li>The matrix <span class="math inline">\(L\)</span> has two complex eigenvalues and one real eigenvalue. How do the complex eigenvectors manifest in the trajectory of a population?</li>
<li>What is the long-term behavior of the herd? Will the size of the herd grow, stablilize or shrink? What will be the proportions of juveniles, yearlings and adults in the herd?</li>
</ol></li>
</ol>
</div>
<div id="solutions-to-practice-problems-2" class="section level2">
<h2><span class="header-section-number">26.3</span> Solutions to Practice Problems</h2>
<ol style="list-style-type: decimal">
<li>There are three eigenvalues: 1, 2, and <span class="math inline">\(-2\)</span>. We find an eigenvector for each of them.
<ul>
<li><p>Eigenvalue <span class="math inline">\(\lambda = 1\)</span>
<span class="math display">\[
A - I = 
\left[
\begin{array}{rrr}
1 &amp; -1 &amp; 0 \\
0 &amp; 0 &amp; 0 \\
-2 &amp; 5 &amp; -3 \\
\end{array}
\right]
\sim
\left[
\begin{array}{rrr}
1 &amp; -1 &amp; 0 \\
0 &amp; 3 &amp; -3 \\
0 &amp; 0 &amp; 0 \\
\end{array}
\right]
\sim
\left[
\begin{array}{rrr}
1 &amp; -1 &amp; 0 \\
0 &amp; 1 &amp; -1 \\
0 &amp; 0 &amp; 0 \\
\end{array}
\right]
\sim
\left[
\begin{array}{rrr}
1 &amp; 0 &amp; -1 \\
0 &amp; 1 &amp; -1 \\
0 &amp; 0 &amp; 0 \\
\end{array}
\right]
\]</span>
So one eigenvector is <span class="math inline">\([1,1,1]^{\top}\)</span></p></li>
<li><p>Eigenvalue <span class="math inline">\(\lambda = 2\)</span>
<span class="math display">\[
A - 2I = 
\left[
\begin{array}{rrr}
0 &amp; -1 &amp; 0 \\
0 &amp; -1 &amp; 0 \\
-2 &amp; 5 &amp; -4 \\
\end{array}
\right]
\sim
\left[
\begin{array}{rrr}
-2 &amp; 5 &amp; -4 \\
0 &amp; -1 &amp; 0 \\
0 &amp; 0 &amp; 0 \\
\end{array}
\right]
\sim
\left[
\begin{array}{rrr}
-2 &amp; 0 &amp; -4 \\
0 &amp; 1 &amp; 0 \\
0 &amp; 0 &amp; 0 \\
\end{array}
\right]
\sim
\left[
\begin{array}{rrr}
1 &amp; 0 &amp; 2 \\
0 &amp; 1 &amp; 0 \\
0 &amp; 0 &amp; 0 \\
\end{array}
\right]
\]</span>
So one eigenvector is <span class="math inline">\([-2,0,1]^{\top}\)</span></p></li>
<li><p>Eigenvalue <span class="math inline">\(\lambda = -2\)</span>
<span class="math display">\[
A - 2I = 
\left[
\begin{array}{rrr}
4 &amp; -1 &amp; 0 \\
0 &amp; 3 &amp; 0 \\
-2 &amp; 5 &amp; 0 \\
\end{array}
\right]
\sim
\left[
\begin{array}{rrr}
4 &amp; 0 &amp; 0 \\
0 &amp; 1 &amp; 0 \\
-2 &amp; 0 &amp; 0 \\
\end{array}
\right]
\sim
\left[
\begin{array}{rrr}
1 &amp; 0 &amp; 0 \\
0 &amp; 1 &amp; 0 \\
0 &amp; 0 &amp; 0 \\
\end{array}
\right]
\]</span>
So one eigenvector is <span class="math inline">\([0,0,1]^{\top}\)</span></p></li>
</ul></li>
<li><ol style="list-style-type: lower-alpha">
<li><p><span class="math inline">\(\lambda=0\)</span> is one eigenvalue. We know that the other eigenvalue is nonzero, since we are mapping onto a line. However, we can’t say anything more without additional information.</p></li>
<li><p>The eigenvalues are <span class="math inline">\(\lambda_1 = 1\)</span> and <span class="math inline">\(\lambda_2=-1\)</span>. Let <span class="math inline">\(L\)</span> be the line of reflection.</p>
<ul>
<li>If <span class="math inline">\(\mathsf{v} = [a,b]^{\top}\)</span> is on <span class="math inline">\(L\)</span>, then <span class="math inline">\(T(\mathsf{v}) = \mathsf{v}\)</span>.</li>
<li>The vector <span class="math inline">\(\mathsf{w} = [-b,a]^{\top}\)</span> is perpendicular to <span class="math inline">\(L\)</span>, so <span class="math inline">\(T(\mathsf{w}) = -\mathsf{w}\)</span>.</li>
</ul></li>
<li><p>The eigenvalues are <span class="math inline">\(\lambda_1 = \lambda_2=-1\)</span> because
<span class="math display">\[
 T\left( \begin{bmatrix} x_1 \\ x_2 \end{bmatrix} \right)
 = \begin{bmatrix} -x_1 \\ -x_2 \end{bmatrix}
 = \begin{bmatrix} -1 &amp; 0 \\ 0 &amp; -1 \end{bmatrix} \begin{bmatrix} x_1 \\ x_2 \end{bmatrix}
 \]</span></p></li>
<li><p>There is one eigenvalue <span class="math inline">\(\lambda=1\)</span> with algebraic multiplicity 2. However, it only has geometric multiplicity 1. We know that a shear matrix is not diagonalizable.</p></li>
</ol></li>
<li><ol style="list-style-type: lower-alpha">
<li><span class="math inline">\(A\)</span> is not invertible because <span class="math inline">\(0\)</span> is an eigenvalue. <span class="math inline">\(A\)</span> is diagonalizable because it have 5 distinct eigenvalues.</li>
<li><span class="math inline">\(B\)</span> is invertible because <span class="math inline">\(0\)</span> is not an eigenvalue. <span class="math inline">\(B\)</span> is diagonalizable because it have 5 distinct eigenvalues.</li>
<li><span class="math inline">\(C\)</span> is invertible because <span class="math inline">\(0\)</span> is not an eigenvalue. We cannot tell whether <span class="math inline">\(C\)</span> is diagonalizable without more information. The eigenvalue <span class="math inline">\(\lambda=2\)</span> has algebraic multiplicity 2. We need to know whether the geometric multiplicity is 1 or 2.</li>
<li><span class="math inline">\(D\)</span> is not invertible because <span class="math inline">\(0\)</span> is an eigenvalue. We cannot tell whether <span class="math inline">\(D\)</span> is diagonalizable without more information. The eigenvalue <span class="math inline">\(\lambda=3\)</span> has algebraic multiplicity 2. We need to know whether the geometric multiplicity is 1 or 2.</li>
</ol></li>
<li><ol style="list-style-type: lower-alpha">
<li>No, <span class="math inline">\(A\)</span> is not invertible because <span class="math inline">\(0\)</span> is an eigenvalue.</li>
<li><span class="math inline">\(\mathsf{v} = [1, -2, 1]^{\top}\)</span> is an eigenvector for <span class="math inline">\(\lambda=0\)</span>. Therefore <span class="math inline">\(\mathsf{v} \in \mbox{Nul}(A)\)</span>.</li>
<li>The vector <span class="math inline">\(\mathsf{v} = [0,1,2]^{\top}\)</span> is an eigenvector for <span class="math inline">\(\lambda=1\)</span>. So this is a steady-state vector. (However, the dynamical system will not converge to this steady state because <span class="math inline">\(\lambda=6\)</span> is the dominant eigenvalue.)</li>
<li>When <span class="math inline">\(A=P D P^{-1}\)</span>, we can find the coordinates of a vector with respect to the eigenbasis via multiplication by <span class="math inline">\(P^{-1}\)</span>.</li>
</ol></li>
</ol>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb210-1"><a href="quiz-3-review.html#cb210-1"></a>Pinv =<span class="kw">cbind</span>(<span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span><span class="op">/</span><span class="dv">6</span>,<span class="dv">0</span>,<span class="dv">1</span><span class="op">/</span><span class="dv">6</span>),<span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span><span class="op">/</span><span class="dv">15</span>,<span class="dv">1</span><span class="op">/</span><span class="dv">5</span>,<span class="op">-</span><span class="dv">1</span><span class="op">/</span><span class="dv">3</span>),<span class="kw">c</span>(<span class="dv">1</span><span class="op">/</span><span class="dv">30</span>,<span class="dv">2</span><span class="op">/</span><span class="dv">5</span>,<span class="dv">1</span><span class="op">/</span><span class="dv">6</span>))</span>
<span id="cb210-2"><a href="quiz-3-review.html#cb210-2"></a>v =<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>)</span>
<span id="cb210-3"><a href="quiz-3-review.html#cb210-3"></a></span>
<span id="cb210-4"><a href="quiz-3-review.html#cb210-4"></a>Pinv <span class="op">%*%</span><span class="st"> </span>v</span></code></pre></div>
<pre><code>##      [,1]
## [1,] -0.2
## [2,]  1.6
## [3,]  0.0</code></pre>
<p>So <span class="math inline">\([ \mathsf{v}]_{\mathcal{B}} = [-1/5, 8/5, 0]^{\top}\)</span>.</p>
<ol start="5" style="list-style-type: lower-alpha">
<li><span class="math inline">\(-\frac{1}{5} \cdot 6^{2020} \cdot \begin{bmatrix} -5 \\ -2 \\ 1 \end{bmatrix} + \frac{8}{5} \cdot \begin{bmatrix} 0 \\ 1 \\ 2 \end{bmatrix}\)</span></li>
</ol>
<ol start="5" style="list-style-type: decimal">
<li><p>This system scales by <span class="math inline">\(\sqrt{1+1} = \sqrt{2}\)</span> and it rotates by <span class="math inline">\(\tan^{-1} (1/1) = \pi/4\)</span>.</p></li>
<li><p>We have
<span class="math display">\[
\begin{bmatrix} a &amp; -b \\ b &amp; a \end{bmatrix} = \begin{bmatrix} .97 &amp; -.71\\ .71 &amp; .97 \end{bmatrix} 
\]</span></p></li>
</ol>
<p>Let’s turn to RStudio</p>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb212-1"><a href="quiz-3-review.html#cb212-1"></a>a =<span class="st"> </span><span class="fl">.97</span></span>
<span id="cb212-2"><a href="quiz-3-review.html#cb212-2"></a>b =<span class="st"> </span><span class="fl">.71</span></span>
<span id="cb212-3"><a href="quiz-3-review.html#cb212-3"></a></span>
<span id="cb212-4"><a href="quiz-3-review.html#cb212-4"></a>scale =<span class="st"> </span><span class="kw">sqrt</span>(a<span class="op">^</span><span class="dv">2</span><span class="op">+</span>b<span class="op">^</span><span class="dv">2</span>)</span>
<span id="cb212-5"><a href="quiz-3-review.html#cb212-5"></a>angle =<span class="st"> </span><span class="kw">atan</span> (b<span class="op">/</span>a)</span>
<span id="cb212-6"><a href="quiz-3-review.html#cb212-6"></a></span>
<span id="cb212-7"><a href="quiz-3-review.html#cb212-7"></a>scale</span></code></pre></div>
<pre><code>## [1] 1.202082</code></pre>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="quiz-3-review.html#cb214-1"></a>angle</span></code></pre></div>
<pre><code>## [1] 0.6318544</code></pre>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb216-1"><a href="quiz-3-review.html#cb216-1"></a><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>pi <span class="op">/</span><span class="st"> </span>angle</span></code></pre></div>
<pre><code>## [1] 9.94404</code></pre>
<ol style="list-style-type: lower-alpha">
<li>It takes 10 iterations to rotate past the <span class="math inline">\(x\)</span>-axis.</li>
<li>We are further from the origin because <span class="math inline">\(| \lambda| \approx 1.2 &gt; 1\)</span>.</li>
</ol>
<ol start="7" style="list-style-type: decimal">
<li><ol style="list-style-type: lower-alpha">
<li>The matrix <span class="math inline">\(A\)</span> is diagonalizable because it has 3 distinct eigenvalues</li>
<li>We must see whether <span class="math inline">\(\lambda=4\)</span> has geometric multiplicty 2 (to match its algebraic multiplicity).</li>
</ol></li>
</ol>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb218-1"><a href="quiz-3-review.html#cb218-1"></a><span class="kw">rref</span>( <span class="kw">cbind</span>(<span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>,<span class="op">-</span><span class="dv">1</span>,<span class="dv">2</span>), <span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>,<span class="op">-</span><span class="dv">1</span>,<span class="dv">2</span>), <span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>,<span class="op">-</span><span class="dv">4</span>)))</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    1   -2
## [2,]    0    0    0
## [3,]    0    0    0</code></pre>
<p>We see that <span class="math inline">\(B - 4I\)</span> has two free columns, so <span class="math inline">\(\dim ( \mbox{Nul}(B-4I))=2\)</span>. This means that <span class="math inline">\(\lambda=4\)</span> has geometric multiplicity 2. Therefore <span class="math inline">\(B\)</span> is diagonalizable.</p>
<ol start="8" style="list-style-type: decimal">
<li><ol style="list-style-type: lower-alpha">
<li>We set <span class="math inline">\(P = \begin{bmatrix} 2 &amp; 1 \\ 3 &amp; -1 \end{bmatrix}\)</span>. So
<span class="math display">\[
 P^{-1} =  - \frac{1}{5} \begin{bmatrix} -1 &amp; -1 \\ -3 &amp; 2 \end{bmatrix}
 = \begin{bmatrix} 0.2 &amp; 0.2 \\ 0.6 &amp; -0.4 \end{bmatrix}
 \]</span>
Or we can find this inverse using RStudio.</li>
</ol></li>
</ol>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb220-1"><a href="quiz-3-review.html#cb220-1"></a>A =<span class="st"> </span><span class="kw">cbind</span>(<span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">3</span>),<span class="kw">c</span>(<span class="dv">1</span>,<span class="op">-</span><span class="dv">1</span>))</span>
<span id="cb220-2"><a href="quiz-3-review.html#cb220-2"></a><span class="kw">solve</span>(A)</span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]  0.2  0.2
## [2,]  0.6 -0.4</code></pre>
<pre><code>Therefore </code></pre>
<p><span class="math display">\[
A = \begin{bmatrix} 0.7 &amp; 0.2 \\ 0.3 &amp; 0.8 \end{bmatrix} = 
\begin{bmatrix} 2 &amp; 1 \\ 3 &amp; -1 \end{bmatrix}
\begin{bmatrix} 1 &amp; 0 \\ 0 &amp; 0.5 \end{bmatrix}
\begin{bmatrix} 0.2 &amp; 0.2 \\ 0.6 &amp; -0.4 \end{bmatrix}
\]</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li><span class="math inline">\(\lim_{n \rightarrow \infty} A^n = \begin{bmatrix} 0.4 &amp; 0.6 \\ 0.4 &amp; 0.6 \end{bmatrix}\)</span> because <span class="math inline">\(\lambda=1\)</span> is the dominant eigenvalue. So each column of <span class="math inline">\(A\)</span> convergence to vector in the eigenspace for the dominant eigenvalue. Basically, we treat each column of <span class="math inline">\(A\)</span> as a “starting vector” repeated multiplication by <span class="math inline">\(A\)</span> converges to the dominant eigenspace. Here are the details.</li>
</ol>
<p>Let <span class="math inline">\(\mathsf{v}_1 = \begin{bmatrix} 2 \\ 3 \end{bmatrix}\)</span> and <span class="math inline">\(\mathsf{v}_2 = \begin{bmatrix} 1 \\ -1 \end{bmatrix}\)</span>. For any constants <span class="math inline">\(c_1, c_2\)</span>, we have
<span class="math display">\[
\lim_{n \rightarrow \infty} A^n (c_1 \mathsf{v}_1 + c_2 \mathsf{v}_2) 
= \lim_{n \rightarrow \infty} \left( c_1 A^n  \mathsf{v}_1 + c_2 A^n \mathsf{v}_2 \right)
= \lim_{n \rightarrow \infty} \left( c_1   \mathsf{v}_1 + c_2 (0.5)^n \mathsf{v}_2 \right)
= c_1   \mathsf{v}_1.
\]</span>
So we need to find <span class="math inline">\(c_1,c_2\)</span> for each column of <span class="math inline">\(A\)</span>. Let’s use R Studio.</p>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb223-1"><a href="quiz-3-review.html#cb223-1"></a>a1 =<span class="st"> </span><span class="kw">c</span>(.<span class="dv">7</span>,.<span class="dv">3</span>)</span>
<span id="cb223-2"><a href="quiz-3-review.html#cb223-2"></a>a2 =<span class="st"> </span><span class="kw">c</span>(.<span class="dv">2</span>,.<span class="dv">8</span>)</span>
<span id="cb223-3"><a href="quiz-3-review.html#cb223-3"></a>P =<span class="st"> </span><span class="kw">cbind</span>(<span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">3</span>), <span class="kw">c</span>(<span class="dv">1</span>,<span class="op">-</span><span class="dv">1</span>))</span>
<span id="cb223-4"><a href="quiz-3-review.html#cb223-4"></a></span>
<span id="cb223-5"><a href="quiz-3-review.html#cb223-5"></a><span class="kw">solve</span>(P,a1)</span></code></pre></div>
<pre><code>## [1] 0.2 0.3</code></pre>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb225-1"><a href="quiz-3-review.html#cb225-1"></a><span class="kw">solve</span>(P,a2)</span></code></pre></div>
<pre><code>## [1]  0.2 -0.2</code></pre>
<p>In each case, <span class="math inline">\(c_1 = 0.2\)</span>. Therefore
<span class="math display">\[
\lim_{n \rightarrow \infty} A^n = \begin{bmatrix} 0.4 &amp; 0.4 \\ 0.6 &amp; 0.6 \end{bmatrix}.
\]</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>We need to find the coefficients for <span class="math inline">\(x_0 = [25, 0]^{\top}\)</span>.</li>
</ol>
<div class="sourceCode" id="cb227"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb227-1"><a href="quiz-3-review.html#cb227-1"></a>P =<span class="st"> </span><span class="kw">cbind</span>(<span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">3</span>), <span class="kw">c</span>(<span class="dv">1</span>,<span class="op">-</span><span class="dv">1</span>))</span>
<span id="cb227-2"><a href="quiz-3-review.html#cb227-2"></a>v =<span class="st"> </span><span class="kw">c</span>(<span class="dv">25</span>,<span class="dv">0</span>)</span>
<span id="cb227-3"><a href="quiz-3-review.html#cb227-3"></a><span class="kw">solve</span>(P,v)</span></code></pre></div>
<pre><code>## [1]  5 15</code></pre>
<pre><code>So the formula is</code></pre>
<p><span class="math display">\[
5 \begin{bmatrix} 2 \\ 3 \end{bmatrix} + 15 \left( \frac{1}{2}  \right)^n \begin{bmatrix} 1 \\ -1 \end{bmatrix} 
\]</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>This converges to <span class="math inline">\(5 \begin{bmatrix} 2 \\ 3 \end{bmatrix}\)</span>.</li>
</ol>
<ol start="9" style="list-style-type: decimal">
<li><ol style="list-style-type: lower-alpha">
<li>We have
<span class="math display">\[
A = \left[
\begin{array}{cc}
 \frac{1}{2} &amp; \frac{1}{5} \\
 -\frac{2}{5} &amp; \frac{9}{10} \\
\end{array}
\right]
=
\begin{bmatrix}
-1/2 &amp; 1/2 \\ 0 &amp; 1
\end{bmatrix}
\begin{bmatrix}
0.7 &amp; -0.2 \\ 0.2 &amp; 0.7
\end{bmatrix}
\begin{bmatrix}
-2 &amp; 1 \\ 0 &amp; 1
\end{bmatrix}
\]</span>
Here are some R calculations to check the answer for (a) and to find the values for (b) and (c).</li>
</ol></li>
</ol>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb230-1"><a href="quiz-3-review.html#cb230-1"></a>A =<span class="st"> </span><span class="kw">cbind</span>(<span class="kw">c</span>(<span class="dv">1</span><span class="op">/</span><span class="dv">2</span>,<span class="op">-</span><span class="dv">2</span><span class="op">/</span><span class="dv">5</span>), <span class="kw">c</span>(<span class="dv">1</span><span class="op">/</span><span class="dv">5</span>,<span class="dv">9</span><span class="op">/</span><span class="dv">10</span>))</span>
<span id="cb230-2"><a href="quiz-3-review.html#cb230-2"></a>A</span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]  0.5  0.2
## [2,] -0.4  0.9</code></pre>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb232-1"><a href="quiz-3-review.html#cb232-1"></a><span class="kw">eigen</span>(A)</span></code></pre></div>
<pre><code>## eigen() decomposition
## $values
## [1] 0.7+0.2i 0.7-0.2i
## 
## $vectors
##                      [,1]                 [,2]
## [1,] 0.4082483-0.4082483i 0.4082483+0.4082483i
## [2,] 0.8164966+0.0000000i 0.8164966+0.0000000i</code></pre>
<div class="sourceCode" id="cb234"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb234-1"><a href="quiz-3-review.html#cb234-1"></a>P =<span class="st"> </span><span class="kw">cbind</span>(<span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span><span class="op">/</span><span class="dv">2</span>,<span class="dv">0</span>),<span class="kw">c</span>(<span class="dv">1</span><span class="op">/</span><span class="dv">2</span>,<span class="dv">1</span>))</span>
<span id="cb234-2"><a href="quiz-3-review.html#cb234-2"></a>C =<span class="st"> </span><span class="kw">cbind</span>(<span class="kw">c</span>(.<span class="dv">7</span>,.<span class="dv">2</span>),<span class="kw">c</span>(<span class="op">-</span>.<span class="dv">2</span>,.<span class="dv">7</span>))</span>
<span id="cb234-3"><a href="quiz-3-review.html#cb234-3"></a>Pinv =<span class="st"> </span><span class="kw">solve</span>(P)</span>
<span id="cb234-4"><a href="quiz-3-review.html#cb234-4"></a></span>
<span id="cb234-5"><a href="quiz-3-review.html#cb234-5"></a>Pinv</span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]   -2    1
## [2,]    0    1</code></pre>
<div class="sourceCode" id="cb236"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb236-1"><a href="quiz-3-review.html#cb236-1"></a>P <span class="op">%*%</span><span class="st"> </span>C <span class="op">%*%</span><span class="st"> </span>Pinv</span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]  0.5  0.2
## [2,] -0.4  0.9</code></pre>
<div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb238-1"><a href="quiz-3-review.html#cb238-1"></a><span class="kw">atan</span>(.<span class="dv">2</span><span class="op">/</span>.<span class="dv">7</span>)</span></code></pre></div>
<pre><code>## [1] 0.2782997</code></pre>
<div class="sourceCode" id="cb240"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb240-1"><a href="quiz-3-review.html#cb240-1"></a><span class="kw">sqrt</span>(.<span class="dv">7</span><span class="op">^</span><span class="dv">2</span> <span class="op">+</span><span class="st"> </span><span class="fl">.2</span><span class="op">^</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 0.728011</code></pre>
<ol start="2" style="list-style-type: lower-alpha">
<li>The angle of rotation is <span class="math inline">\(\tan^{-1} (.2/.7) = 0.278\)</span> radians</li>
<li>The dilation factor is <span class="math inline">\(\sqrt{0.49 + 0.04} = \sqrt{0.53} = 0.728\)</span>.</li>
</ol>
<ol start="10" style="list-style-type: decimal">
<li>Let’s use RStudio.</li>
</ol>
<div class="sourceCode" id="cb242"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb242-1"><a href="quiz-3-review.html#cb242-1"></a>A =<span class="st"> </span><span class="kw">cbind</span>(<span class="kw">c</span>(<span class="fl">0.662</span>, <span class="fl">0.338</span>),<span class="kw">c</span>(<span class="fl">0.25</span>,  <span class="fl">0.75</span>))</span>
<span id="cb242-2"><a href="quiz-3-review.html#cb242-2"></a>A <span class="op">%*%</span><span class="st"> </span>A <span class="op">%*%</span><span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">1</span>)</span></code></pre></div>
<pre><code>##       [,1]
## [1,] 0.353
## [2,] 0.647</code></pre>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb244-1"><a href="quiz-3-review.html#cb244-1"></a>v1 =<span class="st"> </span><span class="kw">c</span>(<span class="op">-</span><span class="fl">0.595</span>, <span class="fl">-0.804</span> )</span>
<span id="cb244-2"><a href="quiz-3-review.html#cb244-2"></a>v1<span class="op">/</span><span class="kw">sum</span>(v1)</span></code></pre></div>
<pre><code>## [1] 0.4253038 0.5746962</code></pre>
<ol style="list-style-type: lower-alpha">
<li>If Monday is dry, then the probability of a wet Wednesday is <span class="math inline">\(0.353\)</span>. The easiest way to calculate this <span class="math inline">\(A^2 \begin{bmatrix} 1 \\ 0 \end{bmatrix}.\)</span></li>
<li>In the long run, <span class="math inline">\(42.5\%\)</span> of days are wet and <span class="math inline">\(57.5\%\)</span> of days are dry.</li>
</ol>
<ol start="11" style="list-style-type: decimal">
<li><ol style="list-style-type: lower-alpha">
<li>Initially, both populations increase from <span class="math inline">\([1, 2]\)</span> to <span class="math inline">\([2.25,2.5]\)</span>, with wolves increasing more quickly. The wolves continue to increase, while the deer start to decrease. After reachaing <span class="math inline">\([3,2]\)</span>, both populations decrease. The deer die out first at the point <span class="math inline">\([.8,0]\)</span>.</li>
<li>Deer breeding: Both populations thrive and grow every year, converging slowly to a <span class="math inline">\(1:1\)</span> ratio. The long-term growth rate is <span class="math inline">\(1.1\)</span>, or <span class="math inline">\(10\%\)</span> growth.</li>
<li>Wolf hunting: Once again, both populations increase. But this time we converge on a stable population of about <span class="math inline">\([2.5, 2.5]\)</span>.</li>
<li>Since they want a stable ecosystem, the wolf hunting is a better option. Ww reach a stable equilibrium population of <span class="math inline">\([2.5, 2.5]\)</span></li>
</ol></li>
<li><ol style="list-style-type: lower-alpha">
<li>Here is the Leslie matrix, as well as some eigensystem computations.</li>
</ol></li>
</ol>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb246-1"><a href="quiz-3-review.html#cb246-1"></a>L =<span class="st"> </span><span class="kw">cbind</span>(<span class="kw">c</span>(<span class="dv">0</span>,.<span class="dv">8</span>,<span class="dv">0</span>),<span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,.<span class="dv">9</span>),<span class="kw">c</span>(.<span class="dv">4</span>,<span class="dv">0</span>,.<span class="dv">8</span>))</span>
<span id="cb246-2"><a href="quiz-3-review.html#cb246-2"></a>L</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]  0.0  0.0  0.4
## [2,]  0.8  0.0  0.0
## [3,]  0.0  0.9  0.8</code></pre>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb248-1"><a href="quiz-3-review.html#cb248-1"></a>syst =<span class="st"> </span><span class="kw">eigen</span>(L)</span>
<span id="cb248-2"><a href="quiz-3-review.html#cb248-2"></a></span>
<span id="cb248-3"><a href="quiz-3-review.html#cb248-3"></a>syst</span></code></pre></div>
<pre><code>## eigen() decomposition
## $values
## [1]  1.0575217+0.0000000i -0.1287609+0.5057227i -0.1287609-0.5057227i
## 
## $vectors
##              [,1]                  [,2]                  [,3]
## [1,] 0.3417536+0i -0.1097728+0.4311448i -0.1097728-0.4311448i
## [2,] 0.2585317+0i  0.6820256+0.0000000i  0.6820256+0.0000000i
## [3,] 0.9035297+0i -0.5097632-0.2775729i -0.5097632+0.2775729i</code></pre>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb250-1"><a href="quiz-3-review.html#cb250-1"></a>syst<span class="op">$</span>vectors[,<span class="dv">1</span>] <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(syst<span class="op">$</span>vectors[,<span class="dv">1</span>])</span></code></pre></div>
<pre><code>## [1] 0.2272578+0i 0.1719172+0i 0.6008250+0i</code></pre>
<ol start="2" style="list-style-type: lower-alpha">
<li>The eigenvalues are <span class="math inline">\(1.058, -0.129 \pm 0.506 i\)</span>.</li>
<li>If we start outside of the span of the dominant eigenvalue, then the trajectory will wiggle with a mild oscillation with an overall growth trend of <span class="math inline">\(1.058\)</span>, or <span class="math inline">\(5.8\%\)</span>.</li>
<li>The size of the herd grows. THe proportions are <span class="math inline">\([0.227, 0.172, 0.601]\)</span>.</li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="quiz-2-review.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
